// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVXTgnfaBzklZe45JOnjJ1MziVpJ3vziU',
    appId: '1:184555083635:web:fe8579ec2f62a73372d706',
    messagingSenderId: '184555083635',
    projectId: 'pawhealth-6db18',
    authDomain: 'pawhealth-6db18.firebaseapp.com',
    storageBucket: 'pawhealth-6db18.firebasestorage.app',
    measurementId: 'G-2PEZJHC4SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-B8cHXllqheQN3ywoVrkDgtz88YUXbyY',
    appId: '1:184555083635:android:db26f15ab36d505f72d706',
    messagingSenderId: '184555083635',
    projectId: 'pawhealth-6db18',
    storageBucket: 'pawhealth-6db18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUw8ruRD6tbBuhqvmk2a7xXHhOu8DJk64',
    appId: '1:184555083635:ios:76dc4241cad58d2072d706',
    messagingSenderId: '184555083635',
    projectId: 'pawhealth-6db18',
    storageBucket: 'pawhealth-6db18.firebasestorage.app',
    iosBundleId: 'com.example.pawhealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUw8ruRD6tbBuhqvmk2a7xXHhOu8DJk64',
    appId: '1:184555083635:ios:76dc4241cad58d2072d706',
    messagingSenderId: '184555083635',
    projectId: 'pawhealth-6db18',
    storageBucket: 'pawhealth-6db18.firebasestorage.app',
    iosBundleId: 'com.example.pawhealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVXTgnfaBzklZe45JOnjJ1MziVpJ3vziU',
    appId: '1:184555083635:web:bdc23b1cfb5cf3a272d706',
    messagingSenderId: '184555083635',
    projectId: 'pawhealth-6db18',
    authDomain: 'pawhealth-6db18.firebaseapp.com',
    storageBucket: 'pawhealth-6db18.firebasestorage.app',
    measurementId: 'G-GVG0MT632V',
  );
}
